; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = ./Software
extra_configs =
    USER_SECRETS_TEMPLATE.ini
    USER_SECRETS.ini

[env:esp32dev]
platform = espressif32
platform_packages=
  framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.4
  framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.4/esp32-arduino-libs-3.0.4.zip
board = esp32dev
monitor_speed = 115200
monitor_filters = default, time, log2file
framework = arduino
extra_scripts = user_secrets_copy.py
build_flags =
  -I include
  '-D WIFI_SSID="${secret.WIFI_SSID}"'
  '-D WIFI_PASSWORD="${secret.WIFI_PASSWORD}"'
  '-D AP_PASSWORD="${secret.AP_PASSWORD}"'
  '-D HTTP_USERNAME="${secret.HTTP_USERNAME}"'
  '-D HTTP_PASSWORD="${secret.HTTP_PASSWORD}"'
  '-D MQTT_SERVER="${secret.MQTT_SERVER}"'
  '-D MQTT_USER="${secret.MQTT_USER}"'
  '-D MQTT_PASSWORD="${secret.MQTT_PASSWORD}"'
lib_deps = 
