// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CYD

#ifndef _CYD_UI_H
#define _CYD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Bat1CellsScreen.h"
#include "screens/ui_FaultsScreen.h"
#include "screens/ui_SecretScreen.h"
#include "screens/ui_Bat2CellsScreen.h"
#include "screens/ui_DoubleBatScreen.h"
#include "screens/ui_SingleBatScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
