/* This file should be renamed to USER_SECRETS.h to be able to use the software!
It contains all the credentials that should never be made public */

//Password to the access point generated by the Battery-Emulator
#define AP_PASSWORD "123456789"  // Minimum of 8 characters; set to blank if you want the access point to be open

//Name and password of Wifi network you want the emulator to connect to
#define WIFI_SSID "REPLACE_WITH_YOUR_SSID"          // Maximum of 63 characters
#define WIFI_PASSWORD "REPLACE_WITH_YOUR_PASSWORD"  // Minimum of 8 characters

//Set WEBSERVER_AUTH_REQUIRED to true to require a password when accessing the webserver homepage. Improves cybersecurity.
#define WEBSERVER_AUTH_REQUIRED false
#define HTTP_USERNAME "admin"  // Username for webserver authentication
#define HTTP_PASSWORD "admin"  // Password for webserver authentication

//MQTT credentials
#define MQTT_SERVER "192.168.xxx.yyy"  // MQTT server address
#define MQTT_PORT 1883                 // MQTT server port
#define MQTT_USER NULL                 // MQTT username, leave blank for no authentication
#define MQTT_PASSWORD NULL             // MQTT password, leave blank for no authentication
