import { readFileSync, writeFileSync } from "node:fs";
import { brotliCompressSync, constants } from "node:zlib";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const frontendRoot = join(__dirname, "..");
const bundlePath = join(frontendRoot, "dist", "app.bundle.js");
const repoRoot = join(frontendRoot, "..");
const outDir = join(repoRoot, "Software", "src", "devboard", "webserver");

const js = readFileSync(bundlePath);
const br = brotliCompressSync(js, {
  params: {
    [constants.BROTLI_PARAM_QUALITY]: constants.BROTLI_MAX_QUALITY,
    [constants.BROTLI_PARAM_MODE]: constants.BROTLI_MODE_TEXT,
  },
});

const hexLines = [];
const perLine = 16;
for (let i = 0; i < br.length; i += perLine) {
  const chunk = br.subarray(i, i + perLine);
  const hex = Array.from(chunk, (b) => `0x${b.toString(16).padStart(2, "0")}`).join(", ");
  hexLines.push(`  ${hex},`);
}

// The embedded SPA bundle is excluded on SMALL_FLASH_DEVICE builds (4 MB
// flash): those images can't fit both UIs. Exception: NEW_WEBUI_ONLY builds
// drop the legacy HTML pages instead, freeing room for the bundle.
const guard = "#if !defined(SMALL_FLASH_DEVICE) || defined(NEW_WEBUI_ONLY)";

const header = `#pragma once
${guard}
#include <cstdint>

extern const uint8_t app_bundle_js_br[];
extern const unsigned int app_bundle_js_br_len;
#endif
`;

const cpp = `// Generated by frontend/scripts/generate-cpp.mjs — do not edit
#include "app_bundle.h"
${guard}

const uint8_t app_bundle_js_br[] = {
${hexLines.join("\n")}
};

const unsigned int app_bundle_js_br_len = ${br.length};
#endif
`;

writeFileSync(join(outDir, "app_bundle.h"), header, "utf8");
writeFileSync(join(outDir, "app_bundle.cpp"), cpp, "utf8");

console.log(`Wrote app_bundle.cpp / app_bundle.h (${br.length} bytes brotli)`);
