import { readFileSync, writeFileSync } from "node:fs";
import { gzipSync } from "node:zlib";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const frontendRoot = join(__dirname, "..");
const bundlePath = join(frontendRoot, "dist", "app.bundle.js");
const repoRoot = join(frontendRoot, "..");
const outDir = join(repoRoot, "Software", "src", "devboard", "webserver");

const js = readFileSync(bundlePath);
const gz = gzipSync(js, { level: 9 });

const hexLines = [];
const perLine = 16;
for (let i = 0; i < gz.length; i += perLine) {
  const chunk = gz.subarray(i, i + perLine);
  const hex = Array.from(chunk, (b) => `0x${b.toString(16).padStart(2, "0")}`).join(", ");
  hexLines.push(`  ${hex},`);
}

const header = `#pragma once
#include <cstdint>

extern const uint8_t app_bundle_js_gz[];
extern const unsigned int app_bundle_js_gz_len;
`;

const cpp = `// Generated by frontend/scripts/generate-cpp.mjs — do not edit
#include "app_bundle.h"

const uint8_t app_bundle_js_gz[] = {
${hexLines.join("\n")}
};

const unsigned int app_bundle_js_gz_len = ${gz.length};
`;

writeFileSync(join(outDir, "app_bundle.h"), header, "utf8");
writeFileSync(join(outDir, "app_bundle.cpp"), cpp, "utf8");

console.log(`Wrote app_bundle.cpp / app_bundle.h (${gz.length} bytes gzip)`);
