// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CYD

#ifndef UI_BAT2CELLSSCREEN_H
#define UI_BAT2CELLSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Bat2CellsScreen
extern void ui_Bat2CellsScreen_screen_init(void);
extern void ui_Bat2CellsScreen_screen_destroy(void);
extern lv_obj_t * ui_Bat2CellsScreen;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_BackS1;
extern void ui_event_BackButS1(lv_event_t * e);
extern lv_obj_t * ui_BackButS1;
extern lv_obj_t * ui_BackTextS1;
extern lv_obj_t * ui_NextS4;
extern void ui_event_NextButS4(lv_event_t * e);
extern lv_obj_t * ui_NextButS4;
extern lv_obj_t * ui_NextTextS3;
extern lv_obj_t * ui_ContainerS1;
extern lv_obj_t * ui_MinVoltagePanelS1;
extern lv_obj_t * ui_CellMin1;
extern lv_obj_t * ui_CellMinValue1;
extern lv_obj_t * ui_MaxVoltagePanelS1;
extern lv_obj_t * ui_CellMax1;
extern lv_obj_t * ui_CellMaxValue1;
extern lv_obj_t * ui_DevPanelS1;
extern lv_obj_t * ui_Dev1;
extern lv_obj_t * ui_DevValue1;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

