// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CYD

#include "../ui.h"

lv_obj_t * ui_Bat2CellsScreen = NULL;
lv_obj_t * ui_Chart1 = NULL;
lv_obj_t * ui_BackS1 = NULL;
lv_obj_t * ui_BackButS1 = NULL;
lv_obj_t * ui_BackTextS1 = NULL;
lv_obj_t * ui_NextS4 = NULL;
lv_obj_t * ui_NextButS4 = NULL;
lv_obj_t * ui_NextTextS3 = NULL;
lv_obj_t * ui_ContainerS1 = NULL;
lv_obj_t * ui_MinVoltagePanelS1 = NULL;
lv_obj_t * ui_CellMin1 = NULL;
lv_obj_t * ui_CellMinValue1 = NULL;
lv_obj_t * ui_MaxVoltagePanelS1 = NULL;
lv_obj_t * ui_CellMax1 = NULL;
lv_obj_t * ui_CellMaxValue1 = NULL;
lv_obj_t * ui_DevPanelS1 = NULL;
lv_obj_t * ui_Dev1 = NULL;
lv_obj_t * ui_DevValue1 = NULL;
lv_obj_t * ui_Label1 = NULL;
// event funtions
void ui_event_BackButS1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Bat1CellsScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Bat1CellsScreen_screen_init);
    }
}

void ui_event_NextButS4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_FaultsScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_FaultsScreen_screen_init);
    }
}

// build funtions

void ui_Bat2CellsScreen_screen_init(void)
{
    ui_Bat2CellsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Bat2CellsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Bat2CellsScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bat2CellsScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart1 = lv_chart_create(ui_Bat2CellsScreen);
    lv_obj_set_width(ui_Chart1, 300);
    lv_obj_set_height(ui_Chart1, 150);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_Chart1, 256);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 0);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_Chart1, 0, 0);
    lv_chart_set_zoom_x(ui_Chart1, 256);
    lv_chart_set_zoom_y(ui_Chart1, 192);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 0, 0, 0, 0, false, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 0, 0, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_chart_series_t * ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);

    ui_BackS1 = lv_obj_create(ui_Bat2CellsScreen);
    lv_obj_remove_style_all(ui_BackS1);
    lv_obj_set_width(ui_BackS1, 50);
    lv_obj_set_height(ui_BackS1, 30);
    lv_obj_set_x(ui_BackS1, 5);
    lv_obj_set_y(ui_BackS1, -5);
    lv_obj_set_align(ui_BackS1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_BackS1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackButS1 = lv_btn_create(ui_BackS1);
    lv_obj_set_width(ui_BackButS1, 50);
    lv_obj_set_height(ui_BackButS1, 30);
    lv_obj_set_align(ui_BackButS1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BackButS1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackButS1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackTextS1 = lv_label_create(ui_BackS1);
    lv_obj_set_width(ui_BackTextS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackTextS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BackTextS1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackTextS1, "Back");

    ui_NextS4 = lv_obj_create(ui_Bat2CellsScreen);
    lv_obj_remove_style_all(ui_NextS4);
    lv_obj_set_width(ui_NextS4, 50);
    lv_obj_set_height(ui_NextS4, 30);
    lv_obj_set_x(ui_NextS4, -5);
    lv_obj_set_y(ui_NextS4, -5);
    lv_obj_set_align(ui_NextS4, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_NextS4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NextButS4 = lv_btn_create(ui_NextS4);
    lv_obj_set_width(ui_NextButS4, 50);
    lv_obj_set_height(ui_NextButS4, 30);
    lv_obj_set_align(ui_NextButS4, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_NextButS4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NextButS4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NextTextS3 = lv_label_create(ui_NextS4);
    lv_obj_set_width(ui_NextTextS3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NextTextS3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NextTextS3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NextTextS3, "Next");

    ui_ContainerS1 = lv_obj_create(ui_Bat2CellsScreen);
    lv_obj_remove_style_all(ui_ContainerS1);
    lv_obj_set_width(ui_ContainerS1, 300);
    lv_obj_set_height(ui_ContainerS1, 30);
    lv_obj_set_x(ui_ContainerS1, 0);
    lv_obj_set_y(ui_ContainerS1, 5);
    lv_obj_set_align(ui_ContainerS1, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_ContainerS1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerS1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContainerS1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MinVoltagePanelS1 = lv_obj_create(ui_ContainerS1);
    lv_obj_set_width(ui_MinVoltagePanelS1, 100);
    lv_obj_set_height(ui_MinVoltagePanelS1, 30);
    lv_obj_set_x(ui_MinVoltagePanelS1, 0);
    lv_obj_set_y(ui_MinVoltagePanelS1, 5);
    lv_obj_set_align(ui_MinVoltagePanelS1, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_MinVoltagePanelS1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_MinVoltagePanelS1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MinVoltagePanelS1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MinVoltagePanelS1, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MinVoltagePanelS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MinVoltagePanelS1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MinVoltagePanelS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CellMin1 = lv_label_create(ui_MinVoltagePanelS1);
    lv_obj_set_width(ui_CellMin1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CellMin1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CellMin1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CellMin1, "Min:");

    ui_CellMinValue1 = lv_label_create(ui_MinVoltagePanelS1);
    lv_obj_set_width(ui_CellMinValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CellMinValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CellMinValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CellMinValue1, "---mV");
    lv_obj_set_style_text_font(ui_CellMinValue1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MaxVoltagePanelS1 = lv_obj_create(ui_ContainerS1);
    lv_obj_set_width(ui_MaxVoltagePanelS1, 100);
    lv_obj_set_height(ui_MaxVoltagePanelS1, 30);
    lv_obj_set_x(ui_MaxVoltagePanelS1, 0);
    lv_obj_set_y(ui_MaxVoltagePanelS1, 5);
    lv_obj_set_align(ui_MaxVoltagePanelS1, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_MaxVoltagePanelS1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_MaxVoltagePanelS1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MaxVoltagePanelS1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MaxVoltagePanelS1, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MaxVoltagePanelS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MaxVoltagePanelS1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MaxVoltagePanelS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CellMax1 = lv_label_create(ui_MaxVoltagePanelS1);
    lv_obj_set_width(ui_CellMax1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CellMax1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CellMax1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CellMax1, "Max:");

    ui_CellMaxValue1 = lv_label_create(ui_MaxVoltagePanelS1);
    lv_obj_set_width(ui_CellMaxValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CellMaxValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CellMaxValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CellMaxValue1, "---mV");
    lv_obj_set_style_text_font(ui_CellMaxValue1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevPanelS1 = lv_obj_create(ui_ContainerS1);
    lv_obj_set_width(ui_DevPanelS1, 100);
    lv_obj_set_height(ui_DevPanelS1, 30);
    lv_obj_set_x(ui_DevPanelS1, 0);
    lv_obj_set_y(ui_DevPanelS1, 5);
    lv_obj_set_align(ui_DevPanelS1, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_DevPanelS1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_DevPanelS1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DevPanelS1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DevPanelS1, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DevPanelS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DevPanelS1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DevPanelS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dev1 = lv_label_create(ui_DevPanelS1);
    lv_obj_set_width(ui_Dev1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Dev1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Dev1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Dev1, "Dev:");

    ui_DevValue1 = lv_label_create(ui_DevPanelS1);
    lv_obj_set_width(ui_DevValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DevValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DevValue1, "---mV");

    ui_Label1 = lv_label_create(ui_Bat2CellsScreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -10);
    lv_obj_set_align(ui_Label1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label1, "Battery 2");

    lv_obj_add_event_cb(ui_BackButS1, ui_event_BackButS1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NextButS4, ui_event_NextButS4, LV_EVENT_ALL, NULL);

}

void ui_Bat2CellsScreen_screen_destroy(void)
{
    if(ui_Bat2CellsScreen) lv_obj_del(ui_Bat2CellsScreen);

    // NULL screen variables
    ui_Bat2CellsScreen = NULL;
    ui_Chart1 = NULL;
    ui_BackS1 = NULL;
    ui_BackButS1 = NULL;
    ui_BackTextS1 = NULL;
    ui_NextS4 = NULL;
    ui_NextButS4 = NULL;
    ui_NextTextS3 = NULL;
    ui_ContainerS1 = NULL;
    ui_MinVoltagePanelS1 = NULL;
    ui_CellMin1 = NULL;
    ui_CellMinValue1 = NULL;
    ui_MaxVoltagePanelS1 = NULL;
    ui_CellMax1 = NULL;
    ui_CellMaxValue1 = NULL;
    ui_DevPanelS1 = NULL;
    ui_Dev1 = NULL;
    ui_DevValue1 = NULL;
    ui_Label1 = NULL;

}
