// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CYD

#ifndef UI_BAT1CELLSSCREEN_H
#define UI_BAT1CELLSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Bat1CellsScreen
extern void ui_Bat1CellsScreen_screen_init(void);
extern void ui_Bat1CellsScreen_screen_destroy(void);
extern lv_obj_t * ui_Bat1CellsScreen;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_BackS2;
extern void ui_event_BackButS2(lv_event_t * e);
extern lv_obj_t * ui_BackButS2;
extern lv_obj_t * ui_BackTextS2;
extern lv_obj_t * ui_NextS2;
extern void ui_event_NextButS2(lv_event_t * e);
extern lv_obj_t * ui_NextButS2;
extern lv_obj_t * ui_NextTextS2;
extern lv_obj_t * ui_ContainerS2;
extern lv_obj_t * ui_MinVoltagePanelS2;
extern lv_obj_t * ui_CellMin;
extern lv_obj_t * ui_CellMinValue;
extern lv_obj_t * ui_MaxVoltagePanelS2;
extern lv_obj_t * ui_CellMax;
extern lv_obj_t * ui_CellMaxValue;
extern lv_obj_t * ui_DevPanelS2;
extern lv_obj_t * ui_Dev;
extern lv_obj_t * ui_DevValue;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

