// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CYD

#include "../ui.h"

lv_obj_t * ui_Bat1CellsScreen = NULL;
lv_obj_t * ui_Chart2 = NULL;
lv_obj_t * ui_BackS2 = NULL;
lv_obj_t * ui_BackButS2 = NULL;
lv_obj_t * ui_BackTextS2 = NULL;
lv_obj_t * ui_NextS2 = NULL;
lv_obj_t * ui_NextButS2 = NULL;
lv_obj_t * ui_NextTextS2 = NULL;
lv_obj_t * ui_ContainerS2 = NULL;
lv_obj_t * ui_MinVoltagePanelS2 = NULL;
lv_obj_t * ui_CellMin = NULL;
lv_obj_t * ui_CellMinValue = NULL;
lv_obj_t * ui_MaxVoltagePanelS2 = NULL;
lv_obj_t * ui_CellMax = NULL;
lv_obj_t * ui_CellMaxValue = NULL;
lv_obj_t * ui_DevPanelS2 = NULL;
lv_obj_t * ui_Dev = NULL;
lv_obj_t * ui_DevValue = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions
void ui_event_BackButS2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DoubleBatScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_DoubleBatScreen_screen_init);
    }
}

void ui_event_NextButS2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Bat2CellsScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Bat2CellsScreen_screen_init);
    }
}

// build funtions

void ui_Bat1CellsScreen_screen_init(void)
{
    ui_Bat1CellsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Bat1CellsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Bat1CellsScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bat1CellsScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart2 = lv_chart_create(ui_Bat1CellsScreen);
    lv_obj_set_width(ui_Chart2, 300);
    lv_obj_set_height(ui_Chart2, 150);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_Chart2, 256);
    lv_chart_set_range(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 0, 0);
    lv_chart_set_range(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_Chart2, 0, 0);
    lv_chart_set_zoom_x(ui_Chart2, 256);
    lv_chart_set_zoom_y(ui_Chart2, 192);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 0, 0, 0, 0, false, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 0, 0, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_chart_series_t * ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart2_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);

    ui_BackS2 = lv_obj_create(ui_Bat1CellsScreen);
    lv_obj_remove_style_all(ui_BackS2);
    lv_obj_set_width(ui_BackS2, 50);
    lv_obj_set_height(ui_BackS2, 30);
    lv_obj_set_x(ui_BackS2, 5);
    lv_obj_set_y(ui_BackS2, -5);
    lv_obj_set_align(ui_BackS2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_BackS2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackButS2 = lv_btn_create(ui_BackS2);
    lv_obj_set_width(ui_BackButS2, 50);
    lv_obj_set_height(ui_BackButS2, 30);
    lv_obj_set_align(ui_BackButS2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BackButS2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackButS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackTextS2 = lv_label_create(ui_BackS2);
    lv_obj_set_width(ui_BackTextS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackTextS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BackTextS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackTextS2, "Back");

    ui_NextS2 = lv_obj_create(ui_Bat1CellsScreen);
    lv_obj_remove_style_all(ui_NextS2);
    lv_obj_set_width(ui_NextS2, 50);
    lv_obj_set_height(ui_NextS2, 30);
    lv_obj_set_x(ui_NextS2, -5);
    lv_obj_set_y(ui_NextS2, -5);
    lv_obj_set_align(ui_NextS2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_NextS2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NextButS2 = lv_btn_create(ui_NextS2);
    lv_obj_set_width(ui_NextButS2, 50);
    lv_obj_set_height(ui_NextButS2, 30);
    lv_obj_set_align(ui_NextButS2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_NextButS2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NextButS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NextTextS2 = lv_label_create(ui_NextS2);
    lv_obj_set_width(ui_NextTextS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NextTextS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NextTextS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NextTextS2, "Next");

    ui_ContainerS2 = lv_obj_create(ui_Bat1CellsScreen);
    lv_obj_remove_style_all(ui_ContainerS2);
    lv_obj_set_width(ui_ContainerS2, 300);
    lv_obj_set_height(ui_ContainerS2, 30);
    lv_obj_set_x(ui_ContainerS2, 0);
    lv_obj_set_y(ui_ContainerS2, 5);
    lv_obj_set_align(ui_ContainerS2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_ContainerS2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerS2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContainerS2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MinVoltagePanelS2 = lv_obj_create(ui_ContainerS2);
    lv_obj_set_width(ui_MinVoltagePanelS2, 100);
    lv_obj_set_height(ui_MinVoltagePanelS2, 30);
    lv_obj_set_x(ui_MinVoltagePanelS2, 0);
    lv_obj_set_y(ui_MinVoltagePanelS2, 5);
    lv_obj_set_align(ui_MinVoltagePanelS2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_MinVoltagePanelS2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_MinVoltagePanelS2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MinVoltagePanelS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MinVoltagePanelS2, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MinVoltagePanelS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MinVoltagePanelS2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MinVoltagePanelS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CellMin = lv_label_create(ui_MinVoltagePanelS2);
    lv_obj_set_width(ui_CellMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CellMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CellMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CellMin, "Min:");

    ui_CellMinValue = lv_label_create(ui_MinVoltagePanelS2);
    lv_obj_set_width(ui_CellMinValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CellMinValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CellMinValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CellMinValue, "---mV");
    lv_obj_set_style_text_font(ui_CellMinValue, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MaxVoltagePanelS2 = lv_obj_create(ui_ContainerS2);
    lv_obj_set_width(ui_MaxVoltagePanelS2, 100);
    lv_obj_set_height(ui_MaxVoltagePanelS2, 30);
    lv_obj_set_x(ui_MaxVoltagePanelS2, 0);
    lv_obj_set_y(ui_MaxVoltagePanelS2, 5);
    lv_obj_set_align(ui_MaxVoltagePanelS2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_MaxVoltagePanelS2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_MaxVoltagePanelS2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MaxVoltagePanelS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MaxVoltagePanelS2, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MaxVoltagePanelS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MaxVoltagePanelS2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MaxVoltagePanelS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CellMax = lv_label_create(ui_MaxVoltagePanelS2);
    lv_obj_set_width(ui_CellMax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CellMax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CellMax, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CellMax, "Max:");

    ui_CellMaxValue = lv_label_create(ui_MaxVoltagePanelS2);
    lv_obj_set_width(ui_CellMaxValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CellMaxValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CellMaxValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CellMaxValue, "---mV");
    lv_obj_set_style_text_font(ui_CellMaxValue, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevPanelS2 = lv_obj_create(ui_ContainerS2);
    lv_obj_set_width(ui_DevPanelS2, 100);
    lv_obj_set_height(ui_DevPanelS2, 30);
    lv_obj_set_x(ui_DevPanelS2, 0);
    lv_obj_set_y(ui_DevPanelS2, 5);
    lv_obj_set_align(ui_DevPanelS2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_DevPanelS2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_DevPanelS2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DevPanelS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DevPanelS2, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DevPanelS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DevPanelS2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DevPanelS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dev = lv_label_create(ui_DevPanelS2);
    lv_obj_set_width(ui_Dev, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Dev, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Dev, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Dev, "Dev:");

    ui_DevValue = lv_label_create(ui_DevPanelS2);
    lv_obj_set_width(ui_DevValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DevValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DevValue, "---mV");

    ui_Label2 = lv_label_create(ui_Bat1CellsScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, -10);
    lv_obj_set_align(ui_Label2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label2, "Battery 1");

    lv_obj_add_event_cb(ui_BackButS2, ui_event_BackButS2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NextButS2, ui_event_NextButS2, LV_EVENT_ALL, NULL);

}

void ui_Bat1CellsScreen_screen_destroy(void)
{
    if(ui_Bat1CellsScreen) lv_obj_del(ui_Bat1CellsScreen);

    // NULL screen variables
    ui_Bat1CellsScreen = NULL;
    ui_Chart2 = NULL;
    ui_BackS2 = NULL;
    ui_BackButS2 = NULL;
    ui_BackTextS2 = NULL;
    ui_NextS2 = NULL;
    ui_NextButS2 = NULL;
    ui_NextTextS2 = NULL;
    ui_ContainerS2 = NULL;
    ui_MinVoltagePanelS2 = NULL;
    ui_CellMin = NULL;
    ui_CellMinValue = NULL;
    ui_MaxVoltagePanelS2 = NULL;
    ui_CellMax = NULL;
    ui_CellMaxValue = NULL;
    ui_DevPanelS2 = NULL;
    ui_Dev = NULL;
    ui_DevValue = NULL;
    ui_Label2 = NULL;

}
