// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CYD

#ifndef UI_DOUBLEBATSCREEN_H
#define UI_DOUBLEBATSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DoubleBatScreen
extern void ui_DoubleBatScreen_screen_init(void);
extern void ui_DoubleBatScreen_screen_destroy(void);
extern lv_obj_t * ui_DoubleBatScreen;
extern lv_obj_t * ui_VoltagePanel;
extern lv_obj_t * ui_VoltageValue;
extern lv_obj_t * ui_LBox;
extern lv_obj_t * ui_SOHPanel;
extern lv_obj_t * ui_SOH;
extern lv_obj_t * ui_SOHValue;
extern lv_obj_t * ui_IsolationRes;
extern lv_obj_t * ui_IsolationText;
extern lv_obj_t * ui_RezistanceValue;
extern lv_obj_t * ui_PowerPanel;
extern lv_obj_t * ui_PowerValue;
extern lv_obj_t * ui_CurrentPanel;
extern lv_obj_t * ui_CurrentValue;
extern lv_obj_t * ui_SOCPanel;
extern lv_obj_t * ui_SOCValue;
extern lv_obj_t * ui_StatusBox;
extern lv_obj_t * ui_InverterStatus1;
extern lv_obj_t * ui_StatusValue;
extern lv_obj_t * ui_TempMinMaxBat1;
extern lv_obj_t * ui_TempMinMaxValueBat1;
extern lv_obj_t * ui_SOCArc;
extern lv_obj_t * ui_Version1;
extern lv_obj_t * ui_RBox;
extern lv_obj_t * ui_SOHPanel2;
extern lv_obj_t * ui_SOH2;
extern lv_obj_t * ui_SOHValue2;
extern lv_obj_t * ui_IsolationRes2;
extern lv_obj_t * ui_IsolationText2;
extern lv_obj_t * ui_RezistanceValue2;
extern lv_obj_t * ui_PowerPanel2;
extern lv_obj_t * ui_PowerValue2;
extern lv_obj_t * ui_CurrentPanel2;
extern lv_obj_t * ui_CurrentValue2;
extern lv_obj_t * ui_VoltagePanel2;
extern lv_obj_t * ui_VoltageValue2;
extern lv_obj_t * ui_SOCPanel2;
extern lv_obj_t * ui_SOCValue2;
extern lv_obj_t * ui_TempMinMaxBat2;
extern lv_obj_t * ui_TempMinMaxValueBat2;
extern lv_obj_t * ui_SOCArc2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Bat1Status;
extern lv_obj_t * ui_Bat2Status;
extern lv_obj_t * ui_NextS1;
extern void ui_event_NextButS1(lv_event_t * e);
extern lv_obj_t * ui_NextButS1;
extern lv_obj_t * ui_NextTextS1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

