// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CYD

#include "../ui.h"

lv_obj_t * ui_DoubleBatScreen = NULL;
lv_obj_t * ui_VoltagePanel = NULL;
lv_obj_t * ui_VoltageValue = NULL;
lv_obj_t * ui_LBox = NULL;
lv_obj_t * ui_SOHPanel = NULL;
lv_obj_t * ui_SOH = NULL;
lv_obj_t * ui_SOHValue = NULL;
lv_obj_t * ui_IsolationRes = NULL;
lv_obj_t * ui_IsolationText = NULL;
lv_obj_t * ui_RezistanceValue = NULL;
lv_obj_t * ui_PowerPanel = NULL;
lv_obj_t * ui_PowerValue = NULL;
lv_obj_t * ui_CurrentPanel = NULL;
lv_obj_t * ui_CurrentValue = NULL;
lv_obj_t * ui_SOCPanel = NULL;
lv_obj_t * ui_SOCValue = NULL;
lv_obj_t * ui_StatusBox = NULL;
lv_obj_t * ui_InverterStatus1 = NULL;
lv_obj_t * ui_StatusValue = NULL;
lv_obj_t * ui_TempMinMaxBat1 = NULL;
lv_obj_t * ui_TempMinMaxValueBat1 = NULL;
lv_obj_t * ui_SOCArc = NULL;
lv_obj_t * ui_Version1 = NULL;
lv_obj_t * ui_RBox = NULL;
lv_obj_t * ui_SOHPanel2 = NULL;
lv_obj_t * ui_SOH2 = NULL;
lv_obj_t * ui_SOHValue2 = NULL;
lv_obj_t * ui_IsolationRes2 = NULL;
lv_obj_t * ui_IsolationText2 = NULL;
lv_obj_t * ui_RezistanceValue2 = NULL;
lv_obj_t * ui_PowerPanel2 = NULL;
lv_obj_t * ui_PowerValue2 = NULL;
lv_obj_t * ui_CurrentPanel2 = NULL;
lv_obj_t * ui_CurrentValue2 = NULL;
lv_obj_t * ui_VoltagePanel2 = NULL;
lv_obj_t * ui_VoltageValue2 = NULL;
lv_obj_t * ui_SOCPanel2 = NULL;
lv_obj_t * ui_SOCValue2 = NULL;
lv_obj_t * ui_TempMinMaxBat2 = NULL;
lv_obj_t * ui_TempMinMaxValueBat2 = NULL;
lv_obj_t * ui_SOCArc2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Bat1Status = NULL;
lv_obj_t * ui_Bat2Status = NULL;
lv_obj_t * ui_NextS1 = NULL;
lv_obj_t * ui_NextButS1 = NULL;
lv_obj_t * ui_NextTextS1 = NULL;
// event funtions
void ui_event_NextButS1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Bat1CellsScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Bat1CellsScreen_screen_init);
    }
}

// build funtions

void ui_DoubleBatScreen_screen_init(void)
{
    ui_DoubleBatScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DoubleBatScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DoubleBatScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DoubleBatScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoltagePanel = lv_obj_create(ui_DoubleBatScreen);
    lv_obj_set_width(ui_VoltagePanel, 80);
    lv_obj_set_height(ui_VoltagePanel, 30);
    lv_obj_set_x(ui_VoltagePanel, -75);
    lv_obj_set_y(ui_VoltagePanel, 55);
    lv_obj_set_align(ui_VoltagePanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_VoltagePanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_VoltagePanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_VoltagePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_VoltagePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VoltagePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_VoltagePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VoltagePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoltageValue = lv_label_create(ui_VoltagePanel);
    lv_obj_set_width(ui_VoltageValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VoltageValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VoltageValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VoltageValue, "--- V");

    ui_LBox = lv_obj_create(ui_DoubleBatScreen);
    lv_obj_remove_style_all(ui_LBox);
    lv_obj_set_width(ui_LBox, 150);
    lv_obj_set_height(ui_LBox, 65);
    lv_obj_set_x(ui_LBox, 5);
    lv_obj_set_y(ui_LBox, 40);
    lv_obj_set_flex_flow(ui_LBox, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_LBox, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_LBox, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SOHPanel = lv_obj_create(ui_LBox);
    lv_obj_set_width(ui_SOHPanel, 75);
    lv_obj_set_height(ui_SOHPanel, 30);
    lv_obj_set_x(ui_SOHPanel, 2);
    lv_obj_set_y(ui_SOHPanel, 24);
    lv_obj_set_align(ui_SOHPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SOHPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SOHPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SOHPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SOHPanel, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SOHPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SOHPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SOHPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOH = lv_label_create(ui_SOHPanel);
    lv_obj_set_width(ui_SOH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SOH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SOH, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SOH, "SOH:");
    lv_obj_set_style_text_font(ui_SOH, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOHValue = lv_label_create(ui_SOHPanel);
    lv_obj_set_width(ui_SOHValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SOHValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SOHValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SOHValue, "---%");
    lv_obj_set_style_text_font(ui_SOHValue, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IsolationRes = lv_obj_create(ui_LBox);
    lv_obj_set_width(ui_IsolationRes, 75);
    lv_obj_set_height(ui_IsolationRes, 30);
    lv_obj_set_align(ui_IsolationRes, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_IsolationRes, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_IsolationRes, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_IsolationRes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IsolationRes, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IsolationRes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_IsolationRes, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_IsolationRes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IsolationText = lv_label_create(ui_IsolationRes);
    lv_obj_set_width(ui_IsolationText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IsolationText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_IsolationText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IsolationText, "Isol:");
    lv_obj_set_style_text_font(ui_IsolationText, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RezistanceValue = lv_label_create(ui_IsolationRes);
    lv_obj_set_width(ui_RezistanceValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RezistanceValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RezistanceValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RezistanceValue, "---");
    lv_obj_set_style_text_font(ui_RezistanceValue, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerPanel = lv_obj_create(ui_LBox);
    lv_obj_set_width(ui_PowerPanel, 75);
    lv_obj_set_height(ui_PowerPanel, 30);
    lv_obj_set_align(ui_PowerPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PowerPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PowerPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PowerPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PowerPanel, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PowerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PowerPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PowerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerValue = lv_label_create(ui_PowerPanel);
    lv_obj_set_width(ui_PowerValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PowerValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PowerValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PowerValue, "--- kW");

    ui_CurrentPanel = lv_obj_create(ui_LBox);
    lv_obj_set_width(ui_CurrentPanel, 75);
    lv_obj_set_height(ui_CurrentPanel, 30);
    lv_obj_set_align(ui_CurrentPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CurrentPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_CurrentPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CurrentPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CurrentPanel, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CurrentPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CurrentPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CurrentPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentValue = lv_label_create(ui_CurrentPanel);
    lv_obj_set_width(ui_CurrentValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CurrentValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentValue, "--- A");

    ui_SOCPanel = lv_obj_create(ui_DoubleBatScreen);
    lv_obj_set_width(ui_SOCPanel, 80);
    lv_obj_set_height(ui_SOCPanel, 30);
    lv_obj_set_x(ui_SOCPanel, -75);
    lv_obj_set_y(ui_SOCPanel, 30);
    lv_obj_set_align(ui_SOCPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SOCPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SOCPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SOCPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SOCPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SOCPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SOCPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SOCPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOCValue = lv_label_create(ui_SOCPanel);
    lv_obj_set_width(ui_SOCValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SOCValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SOCValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SOCValue, "---%");

    ui_StatusBox = lv_obj_create(ui_DoubleBatScreen);
    lv_obj_remove_style_all(ui_StatusBox);
    lv_obj_set_width(ui_StatusBox, 200);
    lv_obj_set_height(ui_StatusBox, 20);
    lv_obj_set_x(ui_StatusBox, 0);
    lv_obj_set_y(ui_StatusBox, -5);
    lv_obj_set_align(ui_StatusBox, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_StatusBox, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_StatusBox, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_StatusBox, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_InverterStatus1 = lv_label_create(ui_StatusBox);
    lv_obj_set_width(ui_InverterStatus1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InverterStatus1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_InverterStatus1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_InverterStatus1, "Status: ");
    lv_obj_set_style_text_font(ui_InverterStatus1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusValue = lv_label_create(ui_StatusBox);
    lv_obj_set_width(ui_StatusValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatusValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StatusValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StatusValue, "---");

    ui_TempMinMaxBat1 = lv_obj_create(ui_DoubleBatScreen);
    lv_obj_set_width(ui_TempMinMaxBat1, 80);
    lv_obj_set_height(ui_TempMinMaxBat1, 30);
    lv_obj_set_x(ui_TempMinMaxBat1, -135);
    lv_obj_set_y(ui_TempMinMaxBat1, -5);
    lv_obj_set_align(ui_TempMinMaxBat1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TempMinMaxBat1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TempMinMaxBat1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TempMinMaxBat1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TempMinMaxBat1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempMinMaxBat1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TempMinMaxBat1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TempMinMaxBat1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempMinMaxValueBat1 = lv_label_create(ui_TempMinMaxBat1);
    lv_obj_set_width(ui_TempMinMaxValueBat1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempMinMaxValueBat1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempMinMaxValueBat1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempMinMaxValueBat1, "--/--°C");
    lv_obj_set_style_text_font(ui_TempMinMaxValueBat1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TempMinMaxValueBat1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TempMinMaxValueBat1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOCArc = lv_arc_create(ui_DoubleBatScreen);
    lv_obj_set_width(ui_SOCArc, 100);
    lv_obj_set_height(ui_SOCArc, 100);
    lv_obj_set_x(ui_SOCArc, -75);
    lv_obj_set_y(ui_SOCArc, 40);
    lv_obj_set_align(ui_SOCArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SOCArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_arc_set_value(ui_SOCArc, 50);

    lv_obj_set_style_arc_color(ui_SOCArc, lv_color_hex(0x40FF4B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SOCArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SOCArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SOCArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Version1 = lv_label_create(ui_DoubleBatScreen);
    lv_obj_set_width(ui_Version1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Version1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Version1, 5);
    lv_obj_set_y(ui_Version1, -5);
    lv_obj_set_align(ui_Version1, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Version1, "Version ...");
    lv_obj_set_style_text_font(ui_Version1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RBox = lv_obj_create(ui_DoubleBatScreen);
    lv_obj_remove_style_all(ui_RBox);
    lv_obj_set_width(ui_RBox, 150);
    lv_obj_set_height(ui_RBox, 65);
    lv_obj_set_x(ui_RBox, -5);
    lv_obj_set_y(ui_RBox, 40);
    lv_obj_set_align(ui_RBox, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_RBox, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_RBox, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_RBox, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SOHPanel2 = lv_obj_create(ui_RBox);
    lv_obj_set_width(ui_SOHPanel2, 75);
    lv_obj_set_height(ui_SOHPanel2, 30);
    lv_obj_set_x(ui_SOHPanel2, 2);
    lv_obj_set_y(ui_SOHPanel2, 24);
    lv_obj_set_align(ui_SOHPanel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SOHPanel2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SOHPanel2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SOHPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SOHPanel2, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SOHPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SOHPanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SOHPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOH2 = lv_label_create(ui_SOHPanel2);
    lv_obj_set_width(ui_SOH2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SOH2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SOH2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SOH2, "SOH:");
    lv_obj_set_style_text_font(ui_SOH2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOHValue2 = lv_label_create(ui_SOHPanel2);
    lv_obj_set_width(ui_SOHValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SOHValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SOHValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SOHValue2, "---%");
    lv_obj_set_style_text_font(ui_SOHValue2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IsolationRes2 = lv_obj_create(ui_RBox);
    lv_obj_set_width(ui_IsolationRes2, 75);
    lv_obj_set_height(ui_IsolationRes2, 30);
    lv_obj_set_align(ui_IsolationRes2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_IsolationRes2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_IsolationRes2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_IsolationRes2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IsolationRes2, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IsolationRes2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_IsolationRes2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_IsolationRes2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IsolationText2 = lv_label_create(ui_IsolationRes2);
    lv_obj_set_width(ui_IsolationText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IsolationText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_IsolationText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IsolationText2, "Isol:");
    lv_obj_set_style_text_font(ui_IsolationText2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RezistanceValue2 = lv_label_create(ui_IsolationRes2);
    lv_obj_set_width(ui_RezistanceValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RezistanceValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RezistanceValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RezistanceValue2, "---");
    lv_obj_set_style_text_font(ui_RezistanceValue2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerPanel2 = lv_obj_create(ui_RBox);
    lv_obj_set_width(ui_PowerPanel2, 75);
    lv_obj_set_height(ui_PowerPanel2, 30);
    lv_obj_set_align(ui_PowerPanel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PowerPanel2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PowerPanel2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PowerPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PowerPanel2, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PowerPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PowerPanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PowerPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerValue2 = lv_label_create(ui_PowerPanel2);
    lv_obj_set_width(ui_PowerValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PowerValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PowerValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PowerValue2, "--- kW");

    ui_CurrentPanel2 = lv_obj_create(ui_RBox);
    lv_obj_set_width(ui_CurrentPanel2, 75);
    lv_obj_set_height(ui_CurrentPanel2, 30);
    lv_obj_set_align(ui_CurrentPanel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CurrentPanel2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_CurrentPanel2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CurrentPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CurrentPanel2, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CurrentPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CurrentPanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CurrentPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentValue2 = lv_label_create(ui_CurrentPanel2);
    lv_obj_set_width(ui_CurrentValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CurrentValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentValue2, "--- A");

    ui_VoltagePanel2 = lv_obj_create(ui_DoubleBatScreen);
    lv_obj_set_width(ui_VoltagePanel2, 80);
    lv_obj_set_height(ui_VoltagePanel2, 30);
    lv_obj_set_x(ui_VoltagePanel2, 75);
    lv_obj_set_y(ui_VoltagePanel2, 55);
    lv_obj_set_align(ui_VoltagePanel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_VoltagePanel2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_VoltagePanel2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_VoltagePanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_VoltagePanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VoltagePanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_VoltagePanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VoltagePanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoltageValue2 = lv_label_create(ui_VoltagePanel2);
    lv_obj_set_width(ui_VoltageValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VoltageValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VoltageValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VoltageValue2, "--- V");

    ui_SOCPanel2 = lv_obj_create(ui_DoubleBatScreen);
    lv_obj_set_width(ui_SOCPanel2, 80);
    lv_obj_set_height(ui_SOCPanel2, 30);
    lv_obj_set_x(ui_SOCPanel2, 75);
    lv_obj_set_y(ui_SOCPanel2, 30);
    lv_obj_set_align(ui_SOCPanel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SOCPanel2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SOCPanel2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SOCPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SOCPanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SOCPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SOCPanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SOCPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOCValue2 = lv_label_create(ui_SOCPanel2);
    lv_obj_set_width(ui_SOCValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SOCValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SOCValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SOCValue2, "---%");

    ui_TempMinMaxBat2 = lv_obj_create(ui_DoubleBatScreen);
    lv_obj_set_width(ui_TempMinMaxBat2, 80);
    lv_obj_set_height(ui_TempMinMaxBat2, 30);
    lv_obj_set_x(ui_TempMinMaxBat2, 135);
    lv_obj_set_y(ui_TempMinMaxBat2, -5);
    lv_obj_set_align(ui_TempMinMaxBat2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TempMinMaxBat2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TempMinMaxBat2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TempMinMaxBat2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TempMinMaxBat2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempMinMaxBat2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TempMinMaxBat2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TempMinMaxBat2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempMinMaxValueBat2 = lv_label_create(ui_TempMinMaxBat2);
    lv_obj_set_width(ui_TempMinMaxValueBat2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempMinMaxValueBat2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempMinMaxValueBat2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempMinMaxValueBat2, "--/--°C");
    lv_obj_set_style_text_font(ui_TempMinMaxValueBat2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TempMinMaxValueBat2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TempMinMaxValueBat2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOCArc2 = lv_arc_create(ui_DoubleBatScreen);
    lv_obj_set_width(ui_SOCArc2, 100);
    lv_obj_set_height(ui_SOCArc2, 100);
    lv_obj_set_x(ui_SOCArc2, 75);
    lv_obj_set_y(ui_SOCArc2, 40);
    lv_obj_set_align(ui_SOCArc2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SOCArc2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_arc_set_value(ui_SOCArc2, 50);

    lv_obj_set_style_arc_color(ui_SOCArc2, lv_color_hex(0x40FF4B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SOCArc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SOCArc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SOCArc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_DoubleBatScreen);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -75);
    lv_obj_set_y(ui_Label3, -90);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Battery 1");

    ui_Label4 = lv_label_create(ui_DoubleBatScreen);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 80);
    lv_obj_set_y(ui_Label4, -90);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Battery 2");

    ui_Bat1Status = lv_label_create(ui_DoubleBatScreen);
    lv_obj_set_width(ui_Bat1Status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Bat1Status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Bat1Status, -75);
    lv_obj_set_y(ui_Bat1Status, -105);
    lv_obj_set_align(ui_Bat1Status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Bat1Status, "---");
    lv_obj_set_style_text_font(ui_Bat1Status, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bat2Status = lv_label_create(ui_DoubleBatScreen);
    lv_obj_set_width(ui_Bat2Status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Bat2Status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Bat2Status, 75);
    lv_obj_set_y(ui_Bat2Status, -105);
    lv_obj_set_align(ui_Bat2Status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Bat2Status, "---");
    lv_obj_set_style_text_font(ui_Bat2Status, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NextS1 = lv_obj_create(ui_DoubleBatScreen);
    lv_obj_remove_style_all(ui_NextS1);
    lv_obj_set_width(ui_NextS1, 50);
    lv_obj_set_height(ui_NextS1, 30);
    lv_obj_set_x(ui_NextS1, -5);
    lv_obj_set_y(ui_NextS1, -5);
    lv_obj_set_align(ui_NextS1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_NextS1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NextButS1 = lv_btn_create(ui_NextS1);
    lv_obj_set_width(ui_NextButS1, 50);
    lv_obj_set_height(ui_NextButS1, 30);
    lv_obj_set_align(ui_NextButS1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_NextButS1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NextButS1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NextTextS1 = lv_label_create(ui_NextS1);
    lv_obj_set_width(ui_NextTextS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NextTextS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NextTextS1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NextTextS1, "Next");

    lv_obj_add_event_cb(ui_NextButS1, ui_event_NextButS1, LV_EVENT_ALL, NULL);

}

void ui_DoubleBatScreen_screen_destroy(void)
{
    if(ui_DoubleBatScreen) lv_obj_del(ui_DoubleBatScreen);

    // NULL screen variables
    ui_DoubleBatScreen = NULL;
    ui_VoltagePanel = NULL;
    ui_VoltageValue = NULL;
    ui_LBox = NULL;
    ui_SOHPanel = NULL;
    ui_SOH = NULL;
    ui_SOHValue = NULL;
    ui_IsolationRes = NULL;
    ui_IsolationText = NULL;
    ui_RezistanceValue = NULL;
    ui_PowerPanel = NULL;
    ui_PowerValue = NULL;
    ui_CurrentPanel = NULL;
    ui_CurrentValue = NULL;
    ui_SOCPanel = NULL;
    ui_SOCValue = NULL;
    ui_StatusBox = NULL;
    ui_InverterStatus1 = NULL;
    ui_StatusValue = NULL;
    ui_TempMinMaxBat1 = NULL;
    ui_TempMinMaxValueBat1 = NULL;
    ui_SOCArc = NULL;
    ui_Version1 = NULL;
    ui_RBox = NULL;
    ui_SOHPanel2 = NULL;
    ui_SOH2 = NULL;
    ui_SOHValue2 = NULL;
    ui_IsolationRes2 = NULL;
    ui_IsolationText2 = NULL;
    ui_RezistanceValue2 = NULL;
    ui_PowerPanel2 = NULL;
    ui_PowerValue2 = NULL;
    ui_CurrentPanel2 = NULL;
    ui_CurrentValue2 = NULL;
    ui_VoltagePanel2 = NULL;
    ui_VoltageValue2 = NULL;
    ui_SOCPanel2 = NULL;
    ui_SOCValue2 = NULL;
    ui_TempMinMaxBat2 = NULL;
    ui_TempMinMaxValueBat2 = NULL;
    ui_SOCArc2 = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_Bat1Status = NULL;
    ui_Bat2Status = NULL;
    ui_NextS1 = NULL;
    ui_NextButS1 = NULL;
    ui_NextTextS1 = NULL;

}
