// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CYD

#ifndef UI_FAULTSSCREEN_H
#define UI_FAULTSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_FaultsScreen
extern void ui_FaultsScreen_screen_init(void);
extern void ui_FaultsScreen_screen_destroy(void);
extern lv_obj_t * ui_FaultsScreen;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_BackS3;
extern void ui_event_BackButS3(lv_event_t * e);
extern lv_obj_t * ui_BackButS3;
extern lv_obj_t * ui_BackTextS3;
extern lv_obj_t * ui_SecretMeniu;
extern void ui_event_NextButS3(lv_event_t * e);
extern lv_obj_t * ui_NextButS3;
extern lv_obj_t * ui_FaultsLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

