// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CYD

#include "../ui.h"

lv_obj_t * ui_FaultsScreen = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_BackS3 = NULL;
lv_obj_t * ui_BackButS3 = NULL;
lv_obj_t * ui_BackTextS3 = NULL;
lv_obj_t * ui_SecretMeniu = NULL;
lv_obj_t * ui_NextButS3 = NULL;
lv_obj_t * ui_FaultsLabel = NULL;
// event funtions
void ui_event_BackButS3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Bat2CellsScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Bat2CellsScreen_screen_init);
    }
}

void ui_event_NextButS3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_screen_change(&ui_SecretScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_SecretScreen_screen_init);
    }
}

// build funtions

void ui_FaultsScreen_screen_init(void)
{
    ui_FaultsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_FaultsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FaultsScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FaultsScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_FaultsScreen);
    lv_obj_set_width(ui_TextArea1, 320);
    lv_obj_set_height(ui_TextArea1, 160);
    lv_obj_set_x(ui_TextArea1, 0);
    lv_obj_set_y(ui_TextArea1, -45);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_BOTTOM_MID);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackS3 = lv_obj_create(ui_FaultsScreen);
    lv_obj_remove_style_all(ui_BackS3);
    lv_obj_set_width(ui_BackS3, 50);
    lv_obj_set_height(ui_BackS3, 30);
    lv_obj_set_x(ui_BackS3, 5);
    lv_obj_set_y(ui_BackS3, -5);
    lv_obj_set_align(ui_BackS3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_BackS3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackButS3 = lv_btn_create(ui_BackS3);
    lv_obj_set_width(ui_BackButS3, 50);
    lv_obj_set_height(ui_BackButS3, 30);
    lv_obj_set_align(ui_BackButS3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BackButS3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackButS3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackTextS3 = lv_label_create(ui_BackS3);
    lv_obj_set_width(ui_BackTextS3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackTextS3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BackTextS3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackTextS3, "Back");

    ui_SecretMeniu = lv_obj_create(ui_FaultsScreen);
    lv_obj_remove_style_all(ui_SecretMeniu);
    lv_obj_set_width(ui_SecretMeniu, 20);
    lv_obj_set_height(ui_SecretMeniu, 20);
    lv_obj_set_x(ui_SecretMeniu, -5);
    lv_obj_set_y(ui_SecretMeniu, 5);
    lv_obj_set_align(ui_SecretMeniu, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_SecretMeniu, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NextButS3 = lv_btn_create(ui_SecretMeniu);
    lv_obj_set_width(ui_NextButS3, 10);
    lv_obj_set_height(ui_NextButS3, 10);
    lv_obj_set_align(ui_NextButS3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_NextButS3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NextButS3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_NextButS3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NextButS3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FaultsLabel = lv_label_create(ui_FaultsScreen);
    lv_obj_set_width(ui_FaultsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FaultsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FaultsLabel, 0);
    lv_obj_set_y(ui_FaultsLabel, -100);
    lv_obj_set_align(ui_FaultsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FaultsLabel, "Faults");

    lv_obj_add_event_cb(ui_BackButS3, ui_event_BackButS3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NextButS3, ui_event_NextButS3, LV_EVENT_ALL, NULL);

}

void ui_FaultsScreen_screen_destroy(void)
{
    if(ui_FaultsScreen) lv_obj_del(ui_FaultsScreen);

    // NULL screen variables
    ui_FaultsScreen = NULL;
    ui_TextArea1 = NULL;
    ui_BackS3 = NULL;
    ui_BackButS3 = NULL;
    ui_BackTextS3 = NULL;
    ui_SecretMeniu = NULL;
    ui_NextButS3 = NULL;
    ui_FaultsLabel = NULL;

}
