// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CYD

#include "../ui.h"

lv_obj_t * ui_SingleBatScreen = NULL;
lv_obj_t * ui_LBox2 = NULL;
lv_obj_t * ui_SOHPanel3 = NULL;
lv_obj_t * ui_SOH3 = NULL;
lv_obj_t * ui_SOHValue3 = NULL;
lv_obj_t * ui_IsolationRes3 = NULL;
lv_obj_t * ui_IsolationText3 = NULL;
lv_obj_t * ui_RezistanceValue3 = NULL;
lv_obj_t * ui_PowerPanel3 = NULL;
lv_obj_t * ui_PowerValue3 = NULL;
lv_obj_t * ui_CurrentPanel3 = NULL;
lv_obj_t * ui_CurrentValue3 = NULL;
lv_obj_t * ui_StatusBox2 = NULL;
lv_obj_t * ui_InverterStatus2 = NULL;
lv_obj_t * ui_StatusValue2 = NULL;
lv_obj_t * ui_SingleBatStatus = NULL;
lv_obj_t * ui_SOCPanel3 = NULL;
lv_obj_t * ui_SOCValue3 = NULL;
lv_obj_t * ui_VoltagePanel3 = NULL;
lv_obj_t * ui_VoltageValue3 = NULL;
lv_obj_t * ui_TempMinMaxSingleBat = NULL;
lv_obj_t * ui_TempMinMaxValueSingleBat = NULL;
lv_obj_t * ui_SOCArc3 = NULL;
lv_obj_t * ui_NextS6 = NULL;
lv_obj_t * ui_NextButS6 = NULL;
lv_obj_t * ui_NextTextS5 = NULL;
lv_obj_t * ui_Version2 = NULL;
// event funtions
void ui_event_NextButS6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Bat1CellsScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Bat1CellsScreen_screen_init);
    }
}

// build funtions

void ui_SingleBatScreen_screen_init(void)
{
    ui_SingleBatScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SingleBatScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SingleBatScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SingleBatScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LBox2 = lv_obj_create(ui_SingleBatScreen);
    lv_obj_remove_style_all(ui_LBox2);
    lv_obj_set_width(ui_LBox2, 150);
    lv_obj_set_height(ui_LBox2, 65);
    lv_obj_set_x(ui_LBox2, 0);
    lv_obj_set_y(ui_LBox2, 40);
    lv_obj_set_align(ui_LBox2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_LBox2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_LBox2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_LBox2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SOHPanel3 = lv_obj_create(ui_LBox2);
    lv_obj_set_width(ui_SOHPanel3, 75);
    lv_obj_set_height(ui_SOHPanel3, 30);
    lv_obj_set_x(ui_SOHPanel3, 2);
    lv_obj_set_y(ui_SOHPanel3, 24);
    lv_obj_set_align(ui_SOHPanel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SOHPanel3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SOHPanel3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SOHPanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SOHPanel3, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SOHPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SOHPanel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SOHPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOH3 = lv_label_create(ui_SOHPanel3);
    lv_obj_set_width(ui_SOH3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SOH3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SOH3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SOH3, "SOH:");
    lv_obj_set_style_text_font(ui_SOH3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOHValue3 = lv_label_create(ui_SOHPanel3);
    lv_obj_set_width(ui_SOHValue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SOHValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SOHValue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SOHValue3, "---%");
    lv_obj_set_style_text_font(ui_SOHValue3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IsolationRes3 = lv_obj_create(ui_LBox2);
    lv_obj_set_width(ui_IsolationRes3, 75);
    lv_obj_set_height(ui_IsolationRes3, 30);
    lv_obj_set_align(ui_IsolationRes3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_IsolationRes3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_IsolationRes3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_IsolationRes3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IsolationRes3, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IsolationRes3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_IsolationRes3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_IsolationRes3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IsolationText3 = lv_label_create(ui_IsolationRes3);
    lv_obj_set_width(ui_IsolationText3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IsolationText3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_IsolationText3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IsolationText3, "Isol:");
    lv_obj_set_style_text_font(ui_IsolationText3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RezistanceValue3 = lv_label_create(ui_IsolationRes3);
    lv_obj_set_width(ui_RezistanceValue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RezistanceValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RezistanceValue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RezistanceValue3, "---");
    lv_obj_set_style_text_font(ui_RezistanceValue3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerPanel3 = lv_obj_create(ui_LBox2);
    lv_obj_set_width(ui_PowerPanel3, 75);
    lv_obj_set_height(ui_PowerPanel3, 30);
    lv_obj_set_align(ui_PowerPanel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PowerPanel3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PowerPanel3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PowerPanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PowerPanel3, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PowerPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PowerPanel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PowerPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerValue3 = lv_label_create(ui_PowerPanel3);
    lv_obj_set_width(ui_PowerValue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PowerValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PowerValue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PowerValue3, "--- kW");

    ui_CurrentPanel3 = lv_obj_create(ui_LBox2);
    lv_obj_set_width(ui_CurrentPanel3, 75);
    lv_obj_set_height(ui_CurrentPanel3, 30);
    lv_obj_set_align(ui_CurrentPanel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CurrentPanel3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_CurrentPanel3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CurrentPanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CurrentPanel3, lv_color_hex(0x6A6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CurrentPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CurrentPanel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CurrentPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentValue3 = lv_label_create(ui_CurrentPanel3);
    lv_obj_set_width(ui_CurrentValue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CurrentValue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentValue3, "--- A");

    ui_StatusBox2 = lv_obj_create(ui_SingleBatScreen);
    lv_obj_remove_style_all(ui_StatusBox2);
    lv_obj_set_width(ui_StatusBox2, 200);
    lv_obj_set_height(ui_StatusBox2, 20);
    lv_obj_set_x(ui_StatusBox2, 0);
    lv_obj_set_y(ui_StatusBox2, -5);
    lv_obj_set_align(ui_StatusBox2, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_StatusBox2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_StatusBox2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_StatusBox2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_InverterStatus2 = lv_label_create(ui_StatusBox2);
    lv_obj_set_width(ui_InverterStatus2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InverterStatus2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_InverterStatus2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_InverterStatus2, "Status: ");
    lv_obj_set_style_text_font(ui_InverterStatus2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusValue2 = lv_label_create(ui_StatusBox2);
    lv_obj_set_width(ui_StatusValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatusValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StatusValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StatusValue2, "---");

    ui_SingleBatStatus = lv_label_create(ui_SingleBatScreen);
    lv_obj_set_width(ui_SingleBatStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SingleBatStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SingleBatStatus, 0);
    lv_obj_set_y(ui_SingleBatStatus, -105);
    lv_obj_set_align(ui_SingleBatStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SingleBatStatus, "---");
    lv_obj_set_style_text_font(ui_SingleBatStatus, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOCPanel3 = lv_obj_create(ui_SingleBatScreen);
    lv_obj_set_width(ui_SOCPanel3, 80);
    lv_obj_set_height(ui_SOCPanel3, 30);
    lv_obj_set_x(ui_SOCPanel3, 0);
    lv_obj_set_y(ui_SOCPanel3, 30);
    lv_obj_set_align(ui_SOCPanel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SOCPanel3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SOCPanel3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SOCPanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SOCPanel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SOCPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SOCPanel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SOCPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOCValue3 = lv_label_create(ui_SOCPanel3);
    lv_obj_set_width(ui_SOCValue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SOCValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SOCValue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SOCValue3, "---%");

    ui_VoltagePanel3 = lv_obj_create(ui_SingleBatScreen);
    lv_obj_set_width(ui_VoltagePanel3, 80);
    lv_obj_set_height(ui_VoltagePanel3, 30);
    lv_obj_set_x(ui_VoltagePanel3, 0);
    lv_obj_set_y(ui_VoltagePanel3, 55);
    lv_obj_set_align(ui_VoltagePanel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_VoltagePanel3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_VoltagePanel3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_VoltagePanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_VoltagePanel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VoltagePanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_VoltagePanel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VoltagePanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoltageValue3 = lv_label_create(ui_VoltagePanel3);
    lv_obj_set_width(ui_VoltageValue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VoltageValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VoltageValue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VoltageValue3, "--- V");

    ui_TempMinMaxSingleBat = lv_obj_create(ui_SingleBatScreen);
    lv_obj_set_width(ui_TempMinMaxSingleBat, 80);
    lv_obj_set_height(ui_TempMinMaxSingleBat, 30);
    lv_obj_set_x(ui_TempMinMaxSingleBat, -70);
    lv_obj_set_y(ui_TempMinMaxSingleBat, -5);
    lv_obj_set_align(ui_TempMinMaxSingleBat, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TempMinMaxSingleBat, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TempMinMaxSingleBat, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TempMinMaxSingleBat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TempMinMaxSingleBat, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempMinMaxSingleBat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TempMinMaxSingleBat, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TempMinMaxSingleBat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempMinMaxValueSingleBat = lv_label_create(ui_TempMinMaxSingleBat);
    lv_obj_set_width(ui_TempMinMaxValueSingleBat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempMinMaxValueSingleBat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempMinMaxValueSingleBat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempMinMaxValueSingleBat, "--/--°C");
    lv_obj_set_style_text_font(ui_TempMinMaxValueSingleBat, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOCArc3 = lv_arc_create(ui_SingleBatScreen);
    lv_obj_set_width(ui_SOCArc3, 100);
    lv_obj_set_height(ui_SOCArc3, 100);
    lv_obj_set_x(ui_SOCArc3, 0);
    lv_obj_set_y(ui_SOCArc3, 40);
    lv_obj_set_align(ui_SOCArc3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SOCArc3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_arc_set_value(ui_SOCArc3, 50);

    lv_obj_set_style_arc_color(ui_SOCArc3, lv_color_hex(0x40FF4B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SOCArc3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SOCArc3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SOCArc3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_NextS6 = lv_obj_create(ui_SingleBatScreen);
    lv_obj_remove_style_all(ui_NextS6);
    lv_obj_set_width(ui_NextS6, 50);
    lv_obj_set_height(ui_NextS6, 30);
    lv_obj_set_x(ui_NextS6, -5);
    lv_obj_set_y(ui_NextS6, -5);
    lv_obj_set_align(ui_NextS6, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_NextS6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NextButS6 = lv_btn_create(ui_NextS6);
    lv_obj_set_width(ui_NextButS6, 50);
    lv_obj_set_height(ui_NextButS6, 30);
    lv_obj_set_align(ui_NextButS6, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_NextButS6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NextButS6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NextTextS5 = lv_label_create(ui_NextS6);
    lv_obj_set_width(ui_NextTextS5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NextTextS5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NextTextS5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NextTextS5, "Next");

    ui_Version2 = lv_label_create(ui_SingleBatScreen);
    lv_obj_set_width(ui_Version2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Version2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Version2, 5);
    lv_obj_set_y(ui_Version2, -5);
    lv_obj_set_align(ui_Version2, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Version2, "Version ...");
    lv_obj_set_style_text_font(ui_Version2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_NextButS6, ui_event_NextButS6, LV_EVENT_ALL, NULL);

}

void ui_SingleBatScreen_screen_destroy(void)
{
    if(ui_SingleBatScreen) lv_obj_del(ui_SingleBatScreen);

    // NULL screen variables
    ui_SingleBatScreen = NULL;
    ui_LBox2 = NULL;
    ui_SOHPanel3 = NULL;
    ui_SOH3 = NULL;
    ui_SOHValue3 = NULL;
    ui_IsolationRes3 = NULL;
    ui_IsolationText3 = NULL;
    ui_RezistanceValue3 = NULL;
    ui_PowerPanel3 = NULL;
    ui_PowerValue3 = NULL;
    ui_CurrentPanel3 = NULL;
    ui_CurrentValue3 = NULL;
    ui_StatusBox2 = NULL;
    ui_InverterStatus2 = NULL;
    ui_StatusValue2 = NULL;
    ui_SingleBatStatus = NULL;
    ui_SOCPanel3 = NULL;
    ui_SOCValue3 = NULL;
    ui_VoltagePanel3 = NULL;
    ui_VoltageValue3 = NULL;
    ui_TempMinMaxSingleBat = NULL;
    ui_TempMinMaxValueSingleBat = NULL;
    ui_SOCArc3 = NULL;
    ui_NextS6 = NULL;
    ui_NextButS6 = NULL;
    ui_NextTextS5 = NULL;
    ui_Version2 = NULL;

}
