// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CYD

#include "../ui.h"

lv_obj_t * ui_SecretScreen = NULL;
lv_obj_t * ui_BackS4 = NULL;
lv_obj_t * ui_BackButS4 = NULL;
lv_obj_t * ui_BackTextS4 = NULL;
lv_obj_t * ui_SettingsContainer = NULL;
lv_obj_t * ui_PauseContainer = NULL;
lv_obj_t * ui_Pause = NULL;
lv_obj_t * ui_PauseText = NULL;
lv_obj_t * ui_OpenContContainer = NULL;
lv_obj_t * ui_OpenContactors = NULL;
lv_obj_t * ui_OpenContactorsText = NULL;
lv_obj_t * ui_RebootLilygoContainer = NULL;
lv_obj_t * ui_Reboot = NULL;
lv_obj_t * ui_RebootText = NULL;
lv_obj_t * ui_WIFIScreenCont = NULL;
lv_obj_t * ui_CYDText = NULL;
lv_obj_t * ui_IPText = NULL;
lv_obj_t * ui_SSIDText = NULL;
lv_obj_t * ui_WifiQualText = NULL;
// event funtions
void ui_event_BackButS4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DoubleBatScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_DoubleBatScreen_screen_init);
    }
}

void ui_event_Pause(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_FaultsScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_FaultsScreen_screen_init);
    }
}

void ui_event_OpenContactors(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_FaultsScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_FaultsScreen_screen_init);
    }
}

void ui_event_Reboot(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_FaultsScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_FaultsScreen_screen_init);
    }
}

// build funtions

void ui_SecretScreen_screen_init(void)
{
    ui_SecretScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SecretScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SecretScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SecretScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackS4 = lv_obj_create(ui_SecretScreen);
    lv_obj_remove_style_all(ui_BackS4);
    lv_obj_set_width(ui_BackS4, 50);
    lv_obj_set_height(ui_BackS4, 30);
    lv_obj_set_x(ui_BackS4, 5);
    lv_obj_set_y(ui_BackS4, -5);
    lv_obj_set_align(ui_BackS4, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_BackS4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackButS4 = lv_btn_create(ui_BackS4);
    lv_obj_set_width(ui_BackButS4, 50);
    lv_obj_set_height(ui_BackButS4, 30);
    lv_obj_set_align(ui_BackButS4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackButS4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackButS4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackTextS4 = lv_label_create(ui_BackS4);
    lv_obj_set_width(ui_BackTextS4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackTextS4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BackTextS4, 0);
    lv_obj_set_y(ui_BackTextS4, 1);
    lv_obj_set_align(ui_BackTextS4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackTextS4, "Back");

    ui_SettingsContainer = lv_obj_create(ui_SecretScreen);
    lv_obj_remove_style_all(ui_SettingsContainer);
    lv_obj_set_width(ui_SettingsContainer, 200);
    lv_obj_set_height(ui_SettingsContainer, 150);
    lv_obj_set_x(ui_SettingsContainer, 0);
    lv_obj_set_y(ui_SettingsContainer, -40);
    lv_obj_set_align(ui_SettingsContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SettingsContainer, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_SettingsContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SettingsContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PauseContainer = lv_obj_create(ui_SettingsContainer);
    lv_obj_remove_style_all(ui_PauseContainer);
    lv_obj_set_width(ui_PauseContainer, 200);
    lv_obj_set_height(ui_PauseContainer, 50);
    lv_obj_set_align(ui_PauseContainer, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PauseContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Pause = lv_btn_create(ui_PauseContainer);
    lv_obj_set_width(ui_Pause, 200);
    lv_obj_set_height(ui_Pause, 30);
    lv_obj_set_align(ui_Pause, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pause, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pause, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PauseText = lv_label_create(ui_PauseContainer);
    lv_obj_set_width(ui_PauseText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PauseText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PauseText, 0);
    lv_obj_set_y(ui_PauseText, 1);
    lv_obj_set_align(ui_PauseText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PauseText, "Pause");

    ui_OpenContContainer = lv_obj_create(ui_SettingsContainer);
    lv_obj_remove_style_all(ui_OpenContContainer);
    lv_obj_set_width(ui_OpenContContainer, 200);
    lv_obj_set_height(ui_OpenContContainer, 50);
    lv_obj_set_align(ui_OpenContContainer, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_OpenContContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OpenContactors = lv_btn_create(ui_OpenContContainer);
    lv_obj_set_width(ui_OpenContactors, 200);
    lv_obj_set_height(ui_OpenContactors, 30);
    lv_obj_set_align(ui_OpenContactors, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OpenContactors, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OpenContactors, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OpenContactorsText = lv_label_create(ui_OpenContContainer);
    lv_obj_set_width(ui_OpenContactorsText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OpenContactorsText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OpenContactorsText, 0);
    lv_obj_set_y(ui_OpenContactorsText, 1);
    lv_obj_set_align(ui_OpenContactorsText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OpenContactorsText, "Open Contactors");

    ui_RebootLilygoContainer = lv_obj_create(ui_SettingsContainer);
    lv_obj_remove_style_all(ui_RebootLilygoContainer);
    lv_obj_set_width(ui_RebootLilygoContainer, 200);
    lv_obj_set_height(ui_RebootLilygoContainer, 50);
    lv_obj_set_align(ui_RebootLilygoContainer, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_RebootLilygoContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Reboot = lv_btn_create(ui_RebootLilygoContainer);
    lv_obj_set_width(ui_Reboot, 200);
    lv_obj_set_height(ui_Reboot, 30);
    lv_obj_set_align(ui_Reboot, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Reboot, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Reboot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RebootText = lv_label_create(ui_RebootLilygoContainer);
    lv_obj_set_width(ui_RebootText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RebootText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RebootText, 0);
    lv_obj_set_y(ui_RebootText, 1);
    lv_obj_set_align(ui_RebootText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RebootText, "Reboot BE");

    ui_WIFIScreenCont = lv_obj_create(ui_SecretScreen);
    lv_obj_remove_style_all(ui_WIFIScreenCont);
    lv_obj_set_width(ui_WIFIScreenCont, 121);
    lv_obj_set_height(ui_WIFIScreenCont, 70);
    lv_obj_set_x(ui_WIFIScreenCont, -20);
    lv_obj_set_y(ui_WIFIScreenCont, -5);
    lv_obj_set_align(ui_WIFIScreenCont, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_flex_flow(ui_WIFIScreenCont, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_WIFIScreenCont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_WIFIScreenCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CYDText = lv_label_create(ui_WIFIScreenCont);
    lv_obj_set_width(ui_CYDText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CYDText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CYDText, -5);
    lv_obj_set_y(ui_CYDText, -5);
    lv_obj_set_align(ui_CYDText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CYDText, "CYD IP:");

    ui_IPText = lv_label_create(ui_WIFIScreenCont);
    lv_obj_set_width(ui_IPText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IPText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IPText, -5);
    lv_obj_set_y(ui_IPText, -5);
    lv_obj_set_align(ui_IPText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IPText, "IP: ---.---.---.---");

    ui_SSIDText = lv_label_create(ui_WIFIScreenCont);
    lv_obj_set_width(ui_SSIDText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SSIDText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SSIDText, -5);
    lv_obj_set_y(ui_SSIDText, -5);
    lv_obj_set_align(ui_SSIDText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SSIDText, "SSID: ---");

    ui_WifiQualText = lv_label_create(ui_WIFIScreenCont);
    lv_obj_set_width(ui_WifiQualText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiQualText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiQualText, -5);
    lv_obj_set_y(ui_WifiQualText, -5);
    lv_obj_set_align(ui_WifiQualText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiQualText, "--- dBm");

    lv_obj_add_event_cb(ui_BackButS4, ui_event_BackButS4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Pause, ui_event_Pause, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OpenContactors, ui_event_OpenContactors, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Reboot, ui_event_Reboot, LV_EVENT_ALL, NULL);

}

void ui_SecretScreen_screen_destroy(void)
{
    if(ui_SecretScreen) lv_obj_del(ui_SecretScreen);

    // NULL screen variables
    ui_SecretScreen = NULL;
    ui_BackS4 = NULL;
    ui_BackButS4 = NULL;
    ui_BackTextS4 = NULL;
    ui_SettingsContainer = NULL;
    ui_PauseContainer = NULL;
    ui_Pause = NULL;
    ui_PauseText = NULL;
    ui_OpenContContainer = NULL;
    ui_OpenContactors = NULL;
    ui_OpenContactorsText = NULL;
    ui_RebootLilygoContainer = NULL;
    ui_Reboot = NULL;
    ui_RebootText = NULL;
    ui_WIFIScreenCont = NULL;
    ui_CYDText = NULL;
    ui_IPText = NULL;
    ui_SSIDText = NULL;
    ui_WifiQualText = NULL;

}
