// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CYD

#ifndef UI_SECRETSCREEN_H
#define UI_SECRETSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SecretScreen
extern void ui_SecretScreen_screen_init(void);
extern void ui_SecretScreen_screen_destroy(void);
extern lv_obj_t * ui_SecretScreen;
extern lv_obj_t * ui_BackS4;
extern void ui_event_BackButS4(lv_event_t * e);
extern lv_obj_t * ui_BackButS4;
extern lv_obj_t * ui_BackTextS4;
extern lv_obj_t * ui_SettingsContainer;
extern lv_obj_t * ui_PauseContainer;
extern void ui_event_Pause(lv_event_t * e);
extern lv_obj_t * ui_Pause;
extern lv_obj_t * ui_PauseText;
extern lv_obj_t * ui_OpenContContainer;
extern void ui_event_OpenContactors(lv_event_t * e);
extern lv_obj_t * ui_OpenContactors;
extern lv_obj_t * ui_OpenContactorsText;
extern lv_obj_t * ui_RebootLilygoContainer;
extern void ui_event_Reboot(lv_event_t * e);
extern lv_obj_t * ui_Reboot;
extern lv_obj_t * ui_RebootText;
extern lv_obj_t * ui_WIFIScreenCont;
extern lv_obj_t * ui_CYDText;
extern lv_obj_t * ui_IPText;
extern lv_obj_t * ui_SSIDText;
extern lv_obj_t * ui_WifiQualText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

