// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CYD

#ifndef UI_SINGLEBATSCREEN_H
#define UI_SINGLEBATSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SingleBatScreen
extern void ui_SingleBatScreen_screen_init(void);
extern void ui_SingleBatScreen_screen_destroy(void);
extern lv_obj_t * ui_SingleBatScreen;
extern lv_obj_t * ui_LBox2;
extern lv_obj_t * ui_SOHPanel3;
extern lv_obj_t * ui_SOH3;
extern lv_obj_t * ui_SOHValue3;
extern lv_obj_t * ui_IsolationRes3;
extern lv_obj_t * ui_IsolationText3;
extern lv_obj_t * ui_RezistanceValue3;
extern lv_obj_t * ui_PowerPanel3;
extern lv_obj_t * ui_PowerValue3;
extern lv_obj_t * ui_CurrentPanel3;
extern lv_obj_t * ui_CurrentValue3;
extern lv_obj_t * ui_StatusBox2;
extern lv_obj_t * ui_InverterStatus2;
extern lv_obj_t * ui_StatusValue2;
extern lv_obj_t * ui_SingleBatStatus;
extern lv_obj_t * ui_SOCPanel3;
extern lv_obj_t * ui_SOCValue3;
extern lv_obj_t * ui_VoltagePanel3;
extern lv_obj_t * ui_VoltageValue3;
extern lv_obj_t * ui_TempMinMaxSingleBat;
extern lv_obj_t * ui_TempMinMaxValueSingleBat;
extern lv_obj_t * ui_SOCArc3;
extern lv_obj_t * ui_NextS6;
extern void ui_event_NextButS6(lv_event_t * e);
extern lv_obj_t * ui_NextButS6;
extern lv_obj_t * ui_NextTextS5;
extern lv_obj_t * ui_Version2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

