// pauLTU3
// CYD screen integration entry point.
// Testing-only build.
// This version has not been validated on a real high-voltage vehicle or energy system.
// Use it only for development and bench testing until full system validation is done.

#include <Arduino.h>
#include <SPI.h>

#include <lvgl.h>
#include <TFT_eSPI.h>
#include <XPT2046_Touchscreen.h>

// Custom runtime modules used by this project.
#include "espnow_receiver.h"
#include "screen_backlight.h"
#include "screen_network.h"
#include "ui.h"

// The CYD touch controller uses a dedicated SPI wiring layout.
// These values match the board configuration used by this project.

#define XPT2046_IRQ 36
#define XPT2046_MOSI 32
#define XPT2046_MISO 39
#define XPT2046_CLK 25
#define XPT2046_CS 33

// Separate SPI bus instance for the touch controller.
// Keeping touch on its own bus makes the display + touch pairing stable.
SPIClass mySpi = SPIClass(VSPI);

// Concrete XPT2046 touch controller instance.
XPT2046_Touchscreen ts(XPT2046_CS, XPT2046_IRQ);

// Physical panel resolution.
static const uint16_t screenWidth = 320;
static const uint16_t screenHeight = 240;

// LVGL draw buffer.
// The buffer is intentionally smaller than a full screen to save RAM.
static lv_disp_draw_buf_t draw_buf;
static lv_color_t buf[screenWidth * screenHeight / 10];

// Concrete TFT driver instance.
TFT_eSPI tft = TFT_eSPI(screenWidth, screenHeight);

#if LV_USE_LOG != 0
// Route LVGL log output to Serial when LVGL logging is enabled.
void my_print(const char *buf)
{
    Serial.printf(buf);
    Serial.flush();
}
#endif

// LVGL display flush callback.
// LVGL calls this whenever a rectangular area needs to be pushed to the TFT.
void my_disp_flush(lv_disp_drv_t *disp_drv, const lv_area_t *area, lv_color_t *color_p)
{
    // Width and height of the area LVGL wants to update.
    uint32_t w = (area->x2 - area->x1 + 1);
    uint32_t h = (area->y2 - area->y1 + 1);

    // Transfer the updated pixels to the panel.
    tft.startWrite();
    tft.setAddrWindow(area->x1, area->y1, w, h);
    tft.pushColors((uint16_t *)&color_p->full, w * h, true);
    tft.endWrite();

    // Tell LVGL that this flush is finished.
    lv_disp_flush_ready(disp_drv);
}

// LVGL input callback for the XPT2046 touch controller.
void my_touchpad_read(lv_indev_drv_t *indev_drv, lv_indev_data_t *data)
{
    (void)indev_drv;
    uint16_t touchX, touchY;

    // This sequence works reliably with the XPT2046 controller.
    bool touched = (ts.tirqTouched() && ts.touched());

    if (!touched)
    {
        // No press currently active.
        data->state = LV_INDEV_STATE_REL;
    }
    else
    {
        // Read raw touch coordinates from the controller.
        TS_Point p = ts.getPoint();

        // Map raw values to screen coordinates using this panel's calibration.
        touchX = map(p.x, 200, 3700, 1, screenWidth);  /* Touchscreen X calibration */
        touchY = map(p.y, 240, 3800, 1, screenHeight); /* Touchscreen X calibration */

        // Notify LVGL that the screen is pressed.
        data->state = LV_INDEV_STATE_PR;

        // Any valid touch wakes the backlight immediately.
        screen_backlight_note_touch();

        // Provide the mapped touch coordinates to LVGL.
        data->point.x = touchX;
        data->point.y = touchY;
    }
}

void setup()
{
    // Serial is used for runtime logs and debugging.
    Serial.begin(115200);

    // Simple boot banner.
    String LVGL_Arduino = "Hello Arduino! ";
    LVGL_Arduino += String('V') + lv_version_major() + "." + lv_version_minor() + "." + lv_version_patch();

    Serial.println(LVGL_Arduino);
    Serial.println("I am LVGL_Arduino");

    // Start LVGL core.
    lv_init();

#if LV_USE_LOG != 0
    // Register Serial print backend for LVGL logs.
    lv_log_register_print_cb(my_print);
#endif

    // Start the touch SPI bus and touch controller.
    mySpi.begin(XPT2046_CLK, XPT2046_MISO, XPT2046_MOSI, XPT2046_CS);
    ts.begin(mySpi);
    ts.setRotation(1);

    // Start the display driver in landscape mode.
    tft.begin();
    tft.setRotation(1);

    // Give LVGL the working pixel buffer.
    lv_disp_draw_buf_init(&draw_buf, buf, NULL, screenWidth * screenHeight / 10);

    // Register the LVGL display driver.
    static lv_disp_drv_t disp_drv;
    lv_disp_drv_init(&disp_drv);
    disp_drv.hor_res = screenWidth;
    disp_drv.ver_res = screenHeight;
    disp_drv.flush_cb = my_disp_flush;
    disp_drv.draw_buf = &draw_buf;
    lv_disp_drv_register(&disp_drv);

    // Register the LVGL pointer input driver backed by the touch controller.
    static lv_indev_drv_t indev_drv;
    lv_indev_drv_init(&indev_drv);
    indev_drv.type = LV_INDEV_TYPE_POINTER;
    indev_drv.read_cb = my_touchpad_read;
    lv_indev_drv_register(&indev_drv);

    // Build the UI object tree generated by SquareLine.
    ui_init();

    // Start backlight control before the screen begins normal work.
    screen_backlight_init();

    // Start Wi-Fi/AP/web configuration support.
    screen_network_init();

    // Start ESP-NOW receiving and data/UI mapping.
    espnow_receiver_init();

    // Always open the correct main screen after boot.
    espnow_receiver_show_main_screen();

    Serial.println("Setup done");
}

void loop()
{
    // Let LVGL run its internal timers and redraw work.
    lv_timer_handler();

    // Apply display dim/off policy based on inactivity.
    screen_backlight_update();

    // Run Wi-Fi/web/OTA background work.
    screen_network_update();

    // Run ESP-NOW receive/UI logic.
    espnow_receiver_update();

    // Small delay keeps the loop responsive without spinning too aggressively.
    delay(5);
}
