// pauLTU3
// CYD network/web/OTA interface.
// Testing-only build.
// This code is intended for development use and has not been validated on a real system.

// Simple network helper for the CYD screen.
// It owns:
// - AP creation,
// - optional STA connection,
// - web configuration page,
// - OTA update web endpoint.

#pragma once

// Start AP/STA Wi-Fi, load saved settings and start the web server.
void screen_network_init();

// Handle web requests, Wi-Fi reconnect attempts and pending reboot after OTA.
void screen_network_update();

// Returns true when the screen is connected to an external Wi-Fi network.
bool screen_network_is_sta_connected();

// Returns the current STA Wi-Fi channel or -1 if not connected.
int screen_network_sta_channel();

// Returns the current STA SSID string when connected.
const char *screen_network_sta_ssid();

// Returns the current STA IP string when connected.
const char *screen_network_sta_ip();

// Returns the current STA RSSI when connected.
int screen_network_sta_rssi();

// Returns the AP SSID generated by the screen.
const char *screen_network_ap_ssid();

// Returns the device hostname used for mDNS and web identification.
const char *screen_network_hostname();
