"""PlatformIO pre-build script: embed the DTC description files of web_data/dtc in the firmware.

Writes gzipped, whitespace-free copies of the DTC JSON files to dtc_json_autogen.h, which
webserver.cpp serves as /dtc/<file> on devices without SMALL_FLASH_DEVICE. The DTC tables on the
battery pages then get their descriptions without internet, while the copy on GitHub, which can
be newer, still replaces the built-in one and is cached by the browser when reachable.

Only files whose name appears in the firmware sources are embedded, so description files no
battery integration uses yet cost no flash.

The header is regenerated on every build from the files in the checkout and is not committed,
so description changes never touch the firmware sources. A missing or invalid file only prints a
warning: that file is then left out of the build.
"""
import gzip
import json
import os
import re

Import("env")  # noqa: F821 - provided by PlatformIO

PROJECT = env.subst("$PROJECT_DIR")  # noqa: F821
DTC_DIR = os.path.join(PROJECT, "web_data", "dtc")
SRC_DIR = os.path.join(PROJECT, "Software", "src")
OUT = os.path.join(SRC_DIR, "devboard", "webserver", "dtc_json_autogen.h")
PER_LINE = 16
NAME_RE = re.compile(r'"([A-Za-z0-9_]+_dtc\.json)"')


def referenced_names():
    """Names of the DTC files the firmware sources refer to as string literals."""
    names = set()
    for root, _dirs, files in os.walk(SRC_DIR):
        for name in files:
            path = os.path.join(root, name)
            if not name.endswith((".h", ".cpp")) or path == OUT:
                continue
            try:
                with open(path, encoding="utf-8", errors="ignore") as f:
                    names.update(NAME_RE.findall(f.read()))
            except OSError:
                pass
    return names


arrays = []
entries = []
total_json = total_gz = 0
for name in sorted(referenced_names()):
    path = os.path.join(DTC_DIR, name)
    if not os.path.isfile(path):
        continue  # referenced but not written yet; the page falls back to GitHub as before
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, ValueError) as e:
        print(f"embed_dtc_json: {name}: {e} - building without it")
        continue
    compact = json.dumps(data, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    # mtime=0 keeps the output identical for identical input, so a build does not recompile
    # the web server just because the header was rewritten.
    packed = gzip.compress(compact, compresslevel=9, mtime=0)
    total_json += len(compact)
    total_gz += len(packed)
    var = f"DTC_JSON_GZ_{len(entries)}"
    lines = []
    for i in range(0, len(packed), PER_LINE):
        lines.append("    " + " ".join(f"0x{b:02X}," for b in packed[i:i + PER_LINE]))
    arrays.append(
        f"// {name}: {len(compact)} bytes of JSON compress to {len(packed)}.\n"
        f"static const uint8_t {var}[] PROGMEM = {{\n" + "\n".join(lines).rstrip(",") + "\n};\n"
    )
    entries.append(f'    {{"{name}", {var}, sizeof({var})}},')

header = (
    "#pragma once\n"
    "\n"
    "// AUTO-GENERATED by tools/embed_dtc_json.py from web_data/dtc - do not edit.\n"
)

if entries:
    header += (
        f"// {len(entries)} files, {total_json} bytes of JSON compress to {total_gz}.\n"
        "\n"
        "#include <Arduino.h>\n"
        "\n"
        "#define DTC_JSON_EMBEDDED\n"
        "// clang-format off\n"
        + "\n".join(arrays)
        + "\n"
        "struct EmbeddedDtcJson {\n"
        "  const char* name;\n"
        "  const uint8_t* gz;\n"
        "  size_t size;\n"
        "};\n"
        "\n"
        "static const EmbeddedDtcJson DTC_JSON_FILES[] = {\n" + "\n".join(entries) + "\n};\n"
        "// clang-format on\n"
    )
else:
    print("embed_dtc_json: no DTC file could be read - building without the embedded descriptions")
    header += "// No DTC file could be read, so no copy is embedded.\n"

try:
    with open(OUT, encoding="utf-8") as f:
        old = f.read()
except OSError:
    old = ""

if old != header:
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(header)
