"""PlatformIO pre-build script: embed web_data/help/help.json in the firmware.

Writes a gzipped, whitespace-free copy of the help texts to help_json_autogen.h, which
webserver.cpp serves as /help.json on devices without SMALL_FLASH_DEVICE. The help buttons then
work without internet (for example during first setup over the emulator's own access point),
while the copy on GitHub, which can be newer, still refreshes the browser's cache when reachable.

The header is regenerated on every build from the help.json in the checkout and is not
committed, so text changes never touch the firmware sources. A missing or invalid help.json
only prints a warning: the firmware is then built without the embedded copy.
"""
import gzip
import json
import os

Import("env")  # noqa: F821 - provided by PlatformIO

PROJECT = env.subst("$PROJECT_DIR")  # noqa: F821
SRC = os.path.join(PROJECT, "web_data", "help", "help.json")
OUT = os.path.join(PROJECT, "Software", "src", "devboard", "webserver", "help_json_autogen.h")
PER_LINE = 16

header = (
    "#pragma once\n"
    "\n"
    "// AUTO-GENERATED by tools/embed_help_json.py from web_data/help/help.json - do not edit.\n"
)

try:
    with open(SRC, encoding="utf-8") as f:
        data = json.load(f)
    compact = json.dumps(data, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    # mtime=0 keeps the output identical for identical input, so a build does not recompile
    # the web server just because the header was rewritten.
    packed = gzip.compress(compact, compresslevel=9, mtime=0)
    lines = []
    for i in range(0, len(packed), PER_LINE):
        lines.append("    " + " ".join(f"0x{b:02X}," for b in packed[i:i + PER_LINE]))
    header += (
        f"// {len(compact)} bytes of JSON compress to {len(packed)}.\n"
        "\n"
        "#include <Arduino.h>\n"
        "\n"
        "#define HELP_JSON_EMBEDDED\n"
        "// clang-format off\n"
        "static const uint8_t HELP_JSON_GZ[] PROGMEM = {\n" + "\n".join(lines).rstrip(",") + "\n};\n"
        "// clang-format on\n"
    )
except (OSError, ValueError) as e:
    print(f"embed_help_json: {e} - building without the embedded help texts")
    header += "// help.json could not be read, so no copy is embedded.\n"

try:
    with open(OUT, encoding="utf-8") as f:
        old = f.read()
except OSError:
    old = ""

if old != header:
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(header)
