#!/usr/bin/env python3
"""Regenerate the gzipped help loader header.

The loader behind the web interface's help buttons is served straight from flash as /help.js
with `Content-Encoding: gzip`. Edit `help.js` and re-run this to refresh `help_js.h`. Full-line
comments and indentation are dropped before compressing, so the source can stay readable.

    python tools/gen_help_js.py           # rewrite the header
    python tools/gen_help_js.py --check   # fail if the header is out of date (used by pre-commit)
"""
import gzip
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent.parent
WEB = HERE / "Software" / "src" / "devboard" / "webserver"
SRC = WEB / "help.js"
OUT = WEB / "help_js.h"
PER_LINE = 16


def strip(source: str) -> str:
    lines = (line.strip() for line in source.splitlines())
    return "\n".join(line for line in lines if line and not line.startswith("//")) + "\n"


def render() -> tuple[str, int, int]:
    raw = strip(SRC.read_text(encoding="utf-8")).encode("utf-8")
    # mtime=0 keeps the header stable in git when the script has not changed.
    packed = gzip.compress(raw, compresslevel=9, mtime=0)

    lines = []
    for i in range(0, len(packed), PER_LINE):
        chunk = packed[i:i + PER_LINE]
        lines.append("    " + " ".join(f"0x{b:02X}," for b in chunk))
    body = "\n".join(lines).rstrip(",")

    header = (
        "#ifndef _HELP_JS_H\n"
        "#define _HELP_JS_H\n"
        "\n"
        "#include <Arduino.h>\n"
        "\n"
        "// GENERATED by tools/gen_help_js.py from help.js - do not edit by hand.\n"
        "// Served as /help.js with Content-Encoding: gzip straight from flash.\n"
        f"// {len(raw)} bytes of script compress to {len(packed)}.\n"
        "// clang-format off\n"
        f"static const uint8_t HELP_JS_GZ[] PROGMEM = {{\n{body}\n}};\n"
        "// clang-format on\n"
        "\n"
        "#endif\n"
    )
    return header, len(raw), len(packed)


def main() -> int:
    if not SRC.is_file():
        print(f"gen_help_js: missing {SRC}", file=sys.stderr)
        return 1

    header, raw_len, packed_len = render()

    if "--check" in sys.argv[1:]:
        # Compare what the header decompresses to, not its bytes: another zlib build may
        # compress the same script differently.
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        try:
            served = gzip.decompress(bytes(int(b, 16) for b in re.findall(r"0x([0-9A-F]{2})", current)))
        except (OSError, EOFError):
            served = b""
        if served != strip(SRC.read_text(encoding="utf-8")).encode("utf-8"):
            print(f"gen_help_js: {OUT.relative_to(HERE)} is out of date, "
                  "run python tools/gen_help_js.py", file=sys.stderr)
            return 1
        return 0

    OUT.write_text(header, encoding="utf-8", newline="\n")
    print(f"{SRC.name}: {raw_len} bytes -> {packed_len} gzipped ({packed_len * 100.0 / raw_len:.1f}%)")
    print(f"wrote {OUT.relative_to(HERE)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
