#!/usr/bin/env python3
"""Regenerate the gzipped BYD cell-balance page header.

The page is served straight from flash with `Content-Encoding: gzip`, so the
firmware carries the compressed bytes rather than the 16 KB of HTML. Edit
`BYD-ATTO-3-BALANCE-PAGE.html` and re-run this to refresh the header.

    python tools/gen_balance_page.py
"""
import gzip
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent.parent
SRC = HERE / "Software" / "src" / "battery" / "BYD-ATTO-3-BALANCE-PAGE.html"
OUT = HERE / "Software" / "src" / "battery" / "BYD-ATTO-3-BALANCE-HTML.h"
PER_LINE = 16


def main() -> int:
    if not SRC.is_file():
        print(f"gen_balance_page: missing {SRC}", file=sys.stderr)
        return 1

    raw = SRC.read_bytes()
    # mtime=0 so the output is byte-identical for identical input, keeping the
    # header stable in git and lettings CI verify it by regenerating.
    packed = gzip.compress(raw, compresslevel=9, mtime=0)

    lines = []
    for i in range(0, len(packed), PER_LINE):
        chunk = packed[i:i + PER_LINE]
        lines.append("    " + " ".join(f"0x{b:02X}," for b in chunk))
    body = "\n".join(lines).rstrip(",")

    OUT.write_text(
        "#ifndef _BYD_ATTO_3_BALANCE_HTML_H\n"
        "#define _BYD_ATTO_3_BALANCE_HTML_H\n"
        "\n"
        "#include <Arduino.h>\n"
        "\n"
        "// GENERATED by tools/gen_balance_page.py from BYD-ATTO-3-BALANCE-PAGE.html - do not edit by hand.\n"
        "// Served with Content-Encoding: gzip straight from flash, so it never builds a String on\n"
        f"// the heap. {len(raw)} bytes of HTML compress to {len(packed)}.\n"
        "// clang-format off\n"
        f"static const uint8_t BYD_BALANCE_PAGE_GZ[] PROGMEM = {{\n{body}\n}};\n"
        "// clang-format on\n"
        "\n"
        "#endif\n",
        encoding="utf-8",
        newline="\n",
    )

    print(f"{SRC.name}: {len(raw)} bytes -> {len(packed)} gzipped "
          f"({len(packed) * 100.0 / len(raw):.1f}%)")
    print(f"wrote {OUT.relative_to(HERE)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
