import os
import subprocess

Import("env")

# Where we'll write the generated header file to
VERSION_H = os.path.join("Software", "src", "devboard", "utils", "version_autogen.h")


def git(*args):
    return subprocess.check_output(["git", *args], stderr=subprocess.DEVNULL).decode().strip()


def safe(value):
    """Escape a value for use inside a C string literal."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def define(name, value):
    """Emit  #define NAME "value"\n  or empty string when value is None."""
    if value is None:
        return ""
    return f'#define {name} "{safe(value)}"\n'


# 1. Gather the raw data from the environment/repo

# Exact tag (release build)
tag = None
try:
    tag = git("describe", "--tags", "--exact-match")
except subprocess.CalledProcessError:
    pass

# Ancestor tag (dev build base)
ancestor_tag = None
try:
    ancestor_tag = git("describe", "--tags", "--abbrev=0")
except subprocess.CalledProcessError:
    pass

# Full SHA + short form
sha = short_sha = None
try:
    sha = git("rev-parse", "HEAD")
    short_sha = sha[:7]
except subprocess.CalledProcessError:
    pass

branch = None
try:
    ref = git("rev-parse", "--abbrev-ref", "HEAD")
    if ref and ref != "HEAD":
        branch = ref
except subprocess.CalledProcessError:
    pass

# GitHub org + repo name (split from "owner/repo")
github_org = github_repo = None
if repo_full := os.environ.get("GITHUB_REPOSITORY", "").strip():
    if "/" in repo_full:
        github_org, github_repo = repo_full.split("/", 1)

# PR number (passed explicitly from workflow env)
github_pr = os.environ.get("GITHUB_PR", "").strip() or None

# PR head SHA (the actual PR commit, not the synthetic merge commit)
github_pr_head_sha = os.environ.get("GITHUB_PR_HEAD_SHA", "").strip() or None
github_pr_short_head_sha = github_pr_head_sha[:7] if github_pr_head_sha else None


# 2. Generate the header file

new_content = (
    f"#pragma once\n"
    f"\n"
    f"// AUTO-GENERATED by tools/identify_build.py — do not edit.\n"
    f"\n"
    f"{define('GIT_TAG', tag)}"
    f"{define('GIT_ANCESTOR_TAG', ancestor_tag)}"
    f"{define('GIT_SHA', sha)}"
    f"{define('GIT_SHORT_SHA', short_sha)}"
    f"{define('GIT_BRANCH', branch)}"
    f"{define('GITHUB_ORG', github_org)}"
    f"{define('GITHUB_REPO', github_repo)}"
    f"{define('GITHUB_PR', github_pr)}"
    f"{define('GITHUB_PR_HEAD_SHA', github_pr_head_sha)}"
    f"{define('GITHUB_PR_HEAD_SHORT_SHA', github_pr_short_head_sha)}"
    f"\n"
)


# 3. Write file only if changed

try:
    with open(VERSION_H) as f:
        old_content = f.read()
except (FileNotFoundError, IOError):
    old_content = ""

if old_content != new_content:
    with open(VERSION_H, "w") as f:
        f.write(new_content)
